wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  entity: slowmoyang
  offline: False
  id: null
  log_model: False
  project: ${project_name}
  name: ${network_name}
  save_dir: ${paths.full_path}
