_target_: src.models.feedforward.TransFeedForward

prior_weight: 1.0e-5

part_embed_conf:
  hddn_dim: 256
  num_blocks: 1
  nrm: layer
  do_bayesian: False

tve_conf:
  model_dim: 64
  num_sa_layers: 3
  num_ca_layers: 2
  mha_config:
    num_heads: 8
    drp: 0.3
  dense_config:
    hddn_dim: 256
    num_blocks: 1
    nrm: layer
    drp: 0.3
    do_bayesian: False

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.0e-3
  weight_decay: 1.0e-4

# Config dicts to pass to utils and pytorch lightning
sched_conf:
  utils:
    name: cyclicwithwarmup
    epochs_per_cycle: 50
  lightning:
    monitor: valid/total_loss
    interval: step
    frequency: 1
