_target_: src.models.nuflows.NuFlows

embed_config:
  hddn_dim: 256
  num_blocks: 1
  act_o: silu
  act_h: silu

transformer_config:
  dim: 256
  encoder_config:
    num_layers: 4
    num_registers: 4
    do_packed: True
    layer_config:
      dropout: 0.1
      num_heads: 8
  classattention_config:
    num_layers: 2
    layer_config:
      num_heads: 8

flow_config:
  num_stacks: 8
  mlp_width: 128
  mlp_depth: 1
  mlp_act: silu
  tail_bound: 4.0
  dropout: 0.1
  num_bins: 8
  flow_type: coupling
  do_lu: False # Waiting on normflows to approve PR otherwise it wont work with onnx
  init_identity: True

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.0e-3
  weight_decay: 1.0e-3

# Config dicts to pass to utils and pytorch lightning
scheduler:
  _target_: mltools.mltools.lightning_utils.linear_warmup_cosine_decay
  _partial_: true
  warmup_steps: 1_000
  total_steps: null # Replaced by trainer max_steps for a one cycle
