_target_: src.models.nuflows.NuFlows

gen_validation: 10

embed_config:
  hddn_dim: 256
  num_blocks: 1
  act_h: SiLU

transformer_config:
  inpt_dim: 128
  outp_dim: 128
  do_packed: True
  encoder_config:
    dim: 128
    num_layers: 4
    num_registers: 2
    layer_config:
      dropout: 0.1
      num_heads: 8
  classattention_config:
    dim: 128
    num_layers: 2
    do_final_norm: True
    layer_config:
      num_heads: 2
      layerscale_init: null # Don't layerscale a cross attention block!

flow_config:
  num_stacks: 10
  mlp_width: 64
  mlp_depth: 2
  mlp_act: SiLU
  tail_bound: 5.0
  dropout: 0.1
  num_bins: 10
  flow_type: coupling
  do_lu: False
  init_identity: True

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5.0e-4
  weight_decay: 1.0e-5

scheduler:
  _target_: mltools.mltools.lightning_utils.linear_warmup_cosine_decay
  _partial_: true
  total_steps: null # Replaced by trainer max_steps for a one cycle
  warmup_steps: 2000
  init_factor: 1.0e-5
  final_factor: 1.0e-5
