_target_: src.models.nuflows.NuFlows

gen_validation: 10

embed_config:
  hddn_dim: 256
  num_blocks: 1
  act_o: SiLU
  act_h: SiLU

transformer_config:
  inpt_dim: 128
  outp_dim: 128
  do_packed: True
  encoder_config:
    dim: 128
    num_layers: 4
    num_registers: 4
    layer_config:
      dropout: 0.1
      num_heads: 8
  classattention_config:
    dim: 128
    num_layers: 2
    layer_config:
      num_heads: 8

flow_config:
  num_stacks: 8
  mlp_width: 128
  mlp_depth: 1
  mlp_act: SiLU
  tail_bound: 4.0
  dropout: 0.1
  num_bins: 8
  flow_type: coupling
  do_lu: False
  init_identity: True

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.0e-3
  weight_decay: 1.0e-4

scheduler:
  _target_: mltools.mltools.lightning_utils.linear_warmup_cosine_decay
  _partial_: true
  warmup_steps: 10_000
  total_steps: null # Replaced by trainer max_steps for a one cycle
