_target_: src.models.nuflows.NuFlows

embed_config:
  hddn_dim: 128
  num_blocks: 1

transformer_config:
  dim: 64
  num_layers: 4
  layer_config:
    num_heads: 8
    do_self_attn: True

diffusion_config:
  transformer_config:
    num_layers: 4
    layer_config:
      num_heads: 8
      do_self_attn: True
  min_sigma: 0
  max_sigma: 80.0
  ema_sync: 0.999
  p_mean: -1.2
  cosine_config:
    encoding_dim: 16
    scheme: exponential
  sampler_function:
    _target_: mltools.mltools.diffusion.sample_heun
    _partial_: True
  sigma_function:
    _target_: mltools.mltools.diffusion.get_sigmas_karras
    _partial_: True
    n_steps: 50
    rho: 7

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.0e-4
  weight_decay: 1.0e-4

# Config dicts to pass to utils and pytorch lightning
sched_config:
  mltools:
    name: cyclicwithwarmup
    epochs_per_cycle: 50
  lightning:
    monitor: valid/total_loss
    interval: step
    frequency: 1
