# output dir will be created by hydra
data_dir: /home/users/l/leighm/scratch/Data/nu2flows
output_dir: ${oc.env:PROJECT_ROOT}

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}/
