model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.full_path}/checkpoints
  filename: best_{epoch:03d}
  monitor: valid/total_loss
  mode: min
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: valid/total_loss
  mode: min
  patience: 300

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: step

rich_progress:
  _target_: lightning.pytorch.callbacks.RichProgressBar
