# Allows hydra to open up in the original folder of the run
defaults:
  - paths: default.yaml
  - hydra: default.yaml
  - _self_

datasets:
 - ${paths.data_dir}/output_odd.h5

# The name of the model to export
project_name: nu2flows_geant4
network_name: trained_on_even
batch_size: 1024
