_target_: src.datamodules.geant4.Geant4H5DataModule

train_conf:
  data_dir: /srv/beegfs/scratch/groups/dpnc/atlas/ttbar_vflows/data/
  file_list: [nonvirtual_mc16d_spincorr.h5]
  table_name: atlas_even

test_conf:
  data_dir: /srv/beegfs/scratch/groups/dpnc/atlas/ttbar_vflows/data/
  file_list: [nonvirtual_mc16d_spincorr.h5]
  table_name: atlas_odd

loader_conf:
  pin_memory: True
  batch_size: 20
  num_workers: 2

val_frac: 0.1
